server:
  port: 8081

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/
security:
  basic:
    enabled: false
  user:
    password: wangruyu
    name: wangruyu

