server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/

spring:
  application:
    name: qbms-pc
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/qbms?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: wangruyu
#redis
  redis:
    host: localhost
    port: 6379
    password:
  messages:
    basename: i18n/messages
    encoding: UTF-8
feign:
  hystrix:
    enabled: true
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 60000

security:
  sessions: always
#mybatis
mybatis:
  mapperLocations: classpath:mapper/*.xml

#encoding
web:
  encoding: UTF-8

#logging
logging:
  level:
    cn.qtech.mapper: DEBUG
