server:
  port: 8080
#服务注册
eureka:
  client:
    serviceUrl:
#      defaultZone: http://localhost:8081/eureka/
      defaultZone: http://wangruyu:wangruyu@localhost:8081/eureka/

#服务网关
zuul:
  routes:
    pc_url:
      path: /pc/**
      serviceId: qbms-pc
      sensitiveHeaders:
    ui_url:
      path: /ui/**
      serviceId: qbms-ui
      sensitiveHeaders:
    manager_url:
      path: /manager/**
      serviceId: qbms-manager
      sensitiveHeaders:
feign:
  hystrix:
    enabled: true
ribbon:
  eureka:
    enabled: true
  ReadTimeout: 60000
  ConnectTimeout: 60000
hystrix:
#  shareSecurityContext: true
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 60000

spring:
  application:
    name: qbms-ui
  jmx:
      default-domain: ${spring.application.name}
#redis
  redis:
    host: localhost
    port: 6379
    password:
  messages:
    basename: i18n/messages
    encoding: UTF-8
  rabbitmq:
    host: localhost
    port: 5672
    username: wangruyu
    password: wangruyu
    publisher-confirms: true
    virtual-host: /
    addresses: localhost:5672
#  cloud:
#    stream:
#      bindings:
#        output_channel:       #channelName
#          destination: mydest #destination，或者可以认为是发布－订阅模型里面的topic
#          binder: myRabbit
#      binders:
#        myRabbit:
#          type: rabbit
#          environment:
#            spring:
#              rabbitmq:
#                host: localhost   #rabbitMQ服务器地址
#                port: 5672          #rabbitMQ服务器端口
#                username: wangruyu
#                password: wangruyu
#                virtual-host: /


security:
  sessions: never

#encoding
web:
  encoding: UTF-8

#logging
logging:
  level:
    cn.qtech.mapper: DEBUG